services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      BASE_URL: "http://localhost:3001"
    ports:
      - '3001:3001'
  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    depends_on:
      - server
